language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "personal_site";' -U postgres
- psql -c 'create database "personal_site-test";' -U postgres
script:
- npm test
- npm run build-client
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: ozalkhan
  api_key:
    secure: UdrqDnZv5FJJdS/a3XaRxA88RqQfGPG9ZIXvO7HY+ohbLXyfCePAdR/gFfZrhCu30Il1cereHJz61752wiypTFANZtvAHOuYwdpi9GzKJde22mwcISeCmlDqpsYT4kGOD5wPkT4OP+5D4UBDOC0HE33MlqMIU0LWf9FFHdABFGRNU1fznJvvvpF3CgljnhcmR15T7+IvgSX8fs2XnS5pOIUFp8s4gupSPoxB7ohUPYr9y/y3y5GEMFG+fuqV0qJTZroYN5BrehajDWfme9ZB5q0hoRT/+LaJ/bFc5cq6VPwIG+MTH7bqaOSqrhrlWwC4sUJe35N4w2LLCjLoRjACQ/LAilmBiZqLjVkF1XRNDsbDXZnY1CR6yQ7Q9aL3jiF6/vgk9ixdk1I32jcfAt1y3oVa9jduJkuG1OqJZoRDbZJ0dEefyjWxmd/Rawtrx79KXio+sMV33vXNvleHZ1+CxxQNEgq6nfOyWqDPyAr4LB1oTx30VwkRzCTKZcOaBrl2bTwDP8p3+GcspJuHo3H0lfIcsH3Ke1UKbgIOJS0C0diEgtijkecY7WsUnEjXPAl2OU1WTxvYLiHF7HB69QHd1EAZie4e0XSUOgCoM3S7ukJsJNtJL+HNCBZSlyZVYQOXkxKVz7WFA2Y/cXyAjjr6VTfNKOQI2BSiuxlwnXlCXnk=
